### ISSUE TITLE
Interface des Generic Blockchain Connector festlegen

### ISSUE THREAD

**Issue by sikelerd** [darenegade/BookNBlock#10]

**Comment by loelala** [comment]
Mögliche generische Mehtoden wären

- getOffer(publickey)
- insertOffer(Offer) 
- sendMessage(OpenDoorMessage)

**Comment by sikelerd** [comment]
* searchOffer(any)
* getAll()

**Comment by sikelerd** [comment]
* authenticateUser(user)
