### ISSUE TITLE
Login umsetzen

### ISSUE THREAD

**Issue by darenegade** [darenegade/BookNBlock#16]
Login über die Login Maske umsetzen.

Hierzu muss noch geklärt werden, wie dieser genau abläuft.

**Comment by loelala** [comment]
Anforderungen:
- [ ] Der Nutzer wählt beim Anmelden, welche Blockchain Technologie er verwenden will

**Comment by loelala** [comment]
Stand 29.05.18
Bei jeden Login gibt der Nutzer seine Ethereumadresse und seinen private Key ein
