### ISSUE TITLE
Email mit benötigter Hardware

### ISSUE THREAD

**Issue by peter-mueller** [darenegade/BookNBlock#2]
- [x] Raspberry Pi mit WLAN oder Adapter WLAN
- [x] Relais
- [x] Elektrischer Türöffner
- [x] 2 Netzteile mit richtigen Specs

**Comment by Maxl94** [comment]
* https://www.amazon.de/Elektrischer-T%C3%BCr%C3%B6ffner-Schlie%C3%9Fblech-110x25-Entriegelungshebel/dp/B01NBWJWZ0/ref=redir_mobile_desktop?_encoding=UTF8&__mk_de_DE=%C3%85M%C3%85Z%C3%95%C3%91&keywords=elektrischer%20t%C3%BCr%C3%B6ffner&pi=AC_SX236_SY340_FMwebp_QL65&qid=1524581027&ref_=mp_s_a_1_14&sr=8-14

* https://www.amazon.de/Raspberry-Pi-Official-Desktop-Starter/dp/B01CI5879A/ref=sr_1_cc_3?s=aps&ie=UTF8&qid=1524987873&sr=1-3-catcorr&keywords=raspberry+pi+3b

* https://www.amazon.de/dp/B01NBW0Z5J/ref=sspa_dk_detail_3?psc=1

* https://www.amazon.de/Salcar-12V-Netzteil-f%C3%BCr-DVD-Player/dp/B01AA83VHA/ref=sr_1_3_sspa?s=ce-de&ie=UTF8&qid=1524987970&sr=1-3-spons&keywords=12v+netzteil&psc=1

**Comment by Maxl94** [comment]
Alles da
