### ISSUE TITLE
Aufgabenbeschreibung anpassen: CheckIn/Out

### ISSUE THREAD

**Issue by darenegade** [darenegade/BookNBlock#28]
In der Aufgabenbeschreibung ist für das Angebot von CheckIn/Out die rede. Nach Rücksprache mit @sikelerd ist damit aber nicht der Zeitraum der Miete gemeint, sondern der Zeitraum, für den das Inserat gültig sein soll. Hier sollte das Naming angepasst werden, um Verwirrungen zu vermeiden.

Im Grunde sollte folgendes möglich sein:
Der __Vermieter__ stellt ein Angebot mit optionalem befristetem Zeitraum ein. D.h. er kann seine Wohnung von Jan-2019 bis Feb-2020 einstellen oder diese Felder einfach leer lassen und das Angebot ist bis zur Löschung gültig.

im Gegensatz dazu kann der __Mieter__ bei seiner Buchung einen Zeitraum wählen. Dies ist allgemein als CheckIn/Out bekannt

**Comment by A-MSG** [comment]
Angepasst
