### ISSUE TITLE
Schnittstellen zum SmartContract definieren

### ISSUE THREAD

**Issue by darenegade** [darenegade/BookNBlock#31]
Welche Schnittstellen soll der SmartContract unabhängig von der Technologie haben?
Wie heißen diese genau und welche Parameter müssen übergeben werden bzw. was kommt zurück?

Aktuelle Schnittstellen (Update: 29.5):

1. `insertOffer` mit sämtlichen Parametern eines Angebotes aus dem Datenmodell
2. `deleteOffer` mit der ID vom Offer
3. `rentAnOffer` mit sämtlichen Parametern einer Buchung aus dem  Datenmodell
4. `getOfferIDs() return uint[]`
5. `getFreeOfferIDs(uint256 from, uint256 to) return uint[]`
6. `getOffer(uint offerID) return (uint price, string ownerName, .....)`
7. `getBookingIDsForOffer(uint offerID) return uint`
8. `getBooking(uint bookingID) return (uint checkIn, uint checkOut, .....)`
9. `isAllowedAt(uint offerID, address renterID, uint256 time) return bool`

In diesem Ticket sollen diese und weitere Schnittstellen fixiert werden und in einer Dokumentation enden.

**Comment by sikelerd** [comment]
Auf jeden Fall brauche ich noch eine Funktion die mir alle Angebote (noch nicht gebucht) zurückliefert.

**Comment by darenegade** [comment]
Bei Etherum-Solidity kann man leider keine komplexen Rückgabewerte liefern. Daher geht keine Liste von Angeboten als Funktion. Ich habe dies einfach mit `public` gekennzeichnet und benötigt daher keinen Getter.

Alternativ: Kann ich eine Art Iterator per Funktion abbilden. Dies macht z.B. bei den Buchungen Sinn, da diese nur von den betroffenen Ver-/Mietern eingesehen werden dürften

Wir können also auf Datenschutz pfeifen oder global den Iterator einsetzen, damit es einheitlich ist. 😄 

Iterator würden dann wie folgt aussehen:

```
getOffersLength() return uint;
getOffer(uint index) return (uint price, string ownerName, .....);
getBookingsLength() return uint;
getBooking(uint index) return (uint checkIn, uint checkOut, .....);
```

**Comment by peter-mueller** [comment]
@darenegade Für die Tür müssen wir wissen ob der Mieter zu dieser Zeit die Erlaubnis hat in die gegebene TürID zu kommen, den Methodennamen kann man evtl. noch verbessern.
```solidity
isAllowedAt(string doorID, string renterID, string[ISO8601-datetime] time) return bool;
```

@Mainau so ok? Ich glaube die DoorID brauchen wir auch in der Methode

```go
func (e *Ethereum) IsAllowedAt(renter door.RenterID, t time.Time) (allowed bool, error) {
	//Annahme: Es existiert ein Contract mit der Methode 'isAllowed(doorID string, renterID string, time time.Time)'
	allowed = e.contract.isAllowedAt(e.DoorID, renter,t)
}
```

**Comment by Mainau** [comment]
Ja, sollte so passen.

**Comment by darenegade** [comment]
@peter-mueller Ich hatte mir vorgestellt, eine ähnliche Funktion einzubauen. Bloß das man keine Zeit übergibt, sondern nur fragt, ob er jetzt Zugriff hat oder nicht. Welche Vorteil siehst du darin, die Zeit selber zu übergeben? In der Regel steht man doch vor der Tür und möchte jetzt rein und nicht wissen, ob man morgen rein darf.

**Comment by sikelerd** [comment]
Leider kann ich auch nicht einfach auf ein public struct Array zugreifen sondern nur auf einzelne Elemente des Arrays, so dass ich ziemlich viele Abfragen stellen um dann danach festzustellen, dass das Angebot schon abgelaufen ist. Wäre es stattdessen möglich ein Array mit den Indexen der noch offenen Angebot zu liefern, so dass ich diese dann laden kann. Ich fände es sehr unschön, wenn ich erst alle Angebot und alle Buchungen laden muss, bevor ich weiß welche Angebote noch offen sind. 
`getOpenOfferIndeces() return uint[]`

**Comment by peter-mueller** [comment]
@darenegade Gibt keinen Grund, ich denke mir nur dass es in solidity per Design keine Möglichkeit gibt die aktuelle Zeit zu kriegen

**Comment by darenegade** [comment]
Wenn ein Block geschrieben wird (Logging?) dann gäbe es schon eine Möglichkeit, aber für den aktuellen Fall hast du recht, dass es keine Zeit in der Chain gibt.

**Comment by loelala** [comment]
Ich habe mir das Authentifizierungskonzept nochmal bisschen genauer angeschaut. Wir benötigen einen eigenen Contract für das Mappen einer Login-Address auf eine Ethereum-Adrresse
Werde da aber Morgen in der Vorlesung auch noch ein bisschen mehr dazu sagen.

**Comment by darenegade** [comment]
Alle hier besprochen Schnittstellen wurden ins Wiki eingepflegt:
https://github.com/darenegade/BookNBlock/wiki/Solidity-Smart-Contract

Falls es noch weiter Schnittstellen gibt, bitte einfach das Ticket wieder öffnen.
