### ISSUE TITLE
Raspberry Pi für Tür vorbereiten

### ISSUE THREAD

**Issue by Maxl94** [darenegade/BookNBlock#33]
- [x]  Go installieren

**Comment by peter-mueller** [comment]
Ich brauche wahrscheinlich einen `geth` node, da ich es aktuell nicht schaff einen ethereum p2p server mit whisper protokoll komplett in go mitzustarten

https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-ARM

**Comment by peter-mueller** [comment]
ok kriegs vllt doch hin, wenn ich aus https://github.com/ethereum/go-ethereum/blob/master/cmd/wnode/main.go klau. Trotzdem wär das geth zur Sicherheit nett
