### ISSUE TITLE
Smart Contract hat keine benamed Return Values sondern nur mit Index

### ISSUE THREAD

**Issue by sikelerd** [darenegade/BookNBlock#46]

**Comment by darenegade** [comment]
Kannst du das Problem genauer beschreiben? Was sind für dich "benamed Return Values"? Welchen Vorteil hat das gegenüber jetzt?

**Comment by sikelerd** [comment]
Zum Beispiel die Methode `getOffer(id)` liefert als Ergebnis ein Array, auf dass ich nur mit Index zugreifen kann. Ich würde gerne mit Namen darauf zugreifen, also zum Beispiel `offer.prize` anstatt `offer[1]`.
