### ISSUE TITLE
DoorID als string im Smart Contract

### ISSUE THREAD

**Issue by sikelerd** [darenegade/BookNBlock#68]
Den Type des Parameters DoorId nach String ändern um eine korrekte Adresse für Whisper eintragen zu können.
Beispiel Adresse: `0x04f0f871df7b11b3a186210ef251d10837ccfb757de9d8669225bcf73632853def72ae7680f8acdfa1ac94345017d2b4c185275a1ea2f7bbe03e939146ba355889`

**Comment by darenegade** [comment]
Der Typ ist schon richtig. Derzeit ist es eine Adresse, was der Public Key der Tür ist ~~und deinem Beispiel entspricht~~. Wahrscheinlich musst du beim formatieren aufpassen.

**Comment by darenegade** [comment]
https://ethereum.stackexchange.com/questions/21010/send-address-to-the-contract-function-from-web3

**Comment by sikelerd** [comment]
Es mag zwar logisch korrekt sein, dass es vom Typ address ist aber das Hilft uns nicht weiter wenn @peter-mueller diesen Wert erwartet und ich ihn nicht in die Blockchain schreiben kann.
Natürlich ist der Wert im Code als String formatiert.
Du kannst gerne mal deine Tests mit diesem Wert ausprobieren. Sie funktionieren auch nicht. Ich kann hier auf UI-Seite nichts machen, also muss es irgendwo anders gelöst werden.

**Comment by sikelerd** [comment]
Den Typ im SmartContract zu ändern ist der schnellste und einfachste Weg. Wenn dir das nicht passt, dann kannst du gerne versuchen in der UI das Problem zu lösen.

**Comment by darenegade** [comment]
@peter-mueller Über das Thema haben wir doch gestern gesprochen. Wird nun doch nicht als Adresse für die Tür die Eth-Address benötigt (Pub-Key)?
Die oben geschriebenen Adresse ist keine ETH-Adresse. Diese sind kürzer und können über eine Checksum geprüft werden, daher kann die obige Adresse auch nicht gespeichert werden.

Eine valide Adresse schaut z.B. so aus: `0x5ffdE78228d8AF84206f2Df40c33a69a163a3455`

Kann es sein, dass dies oben eine generierte Adresse ist für die Whisper-Nachricht?

**Comment by peter-mueller** [comment]
z.B. von der wnode Seite (https://github.com/ethereum/go-ethereum/wiki/Diagnostic-Tool-wnode)

private key: `c74ea2702eb32f523acb118649998e1c8b5690cf0a14bffda7e87b411db3499a`
public key: `04be81a00a90f5c21ead8887eaa254b3f7a37e06f8f2d776dcc46954a228bc50c6fb6dfd155f7e44e6fef9b62fdf6dad041759b864d2cbe4089b6f5c16a817ff46`

sorry, die schauen bei uns einfach so aus, dann ist es einfach keine ETH Adresse, sondern nur ein Public Key (in anderem format)

**Comment by peter-mueller** [comment]
Also jede ETH Adresse ist ein ~Public Key~ gehashter PubKey,
aber natürlich ist nicht jeder Public Key ist eine ETH Adresse.

**Comment by darenegade** [comment]
Das stimmt leider nicht. Die Eth-Adresse ist nur ein Hash aus den letzten 20Bytes des echten PubKeys. Normalerweise übersetzt Eth die Adresse selber auf die PubKey, wie auch immer, aber das geht bei Whisper wohl nicht.
